### ISSUE TITLE
How to generate mask data?

### ISSUE THREAD

**Issue by hksonngan** [tym002/bifurcation_detection#1]
Hi,
Thank you for upload your code.
Could you tell me how to generate the mask date? 
Apply Gaussian to get a heat map like Payer's paper?
Thanks,
Son Tran

**Comment by tym002** [comment]
Hi,
This method does not need a mask to do landmark detection. The output of the model is the pixel location of the landmark. Please see our paper if you need more details. I am happy to answer any further questions. Thank you for your interest.
